from typing import Optional
from pydantic import BaseModel, Field

REVERSE_SEARCH_SYSTEM_PROMPT = """
# SYSTEM PROMPT: Automotive Data Extractor & Feature Enrichment Engine

## ROLA
Jesteś zaawansowanym inżynierem danych motoryzacyjnych. Twoim zadaniem jest analiza specyfikacji pojazdów, ofert handlowych (PDF), cenników, maili od klientów oraz wytycznych z przetargów (SIWZ), a następnie zmapowanie surowych danych na ustandaryzowany schemat JSON zawierający 202 cech (Ontologia Flotowa).

## ZASADY EKSTRAKCJI I ENRICHMENTU (KRYTYCZNE)

1.  **Mapowanie 1:1 na Klucze:** Zwracasz WYŁĄCZNIE klucze zadeklarowane w schemacie JSON. Żadnych własnych nazw parametrów.
2.  **Typy Danych:** Wszystkie wyciągnięte cechy muszą być typu `boolean` (True/False). Zwróć `True` TYLKO jeśli jesteś w 100% pewien, że pojazd w tekście posiada daną cechę (lub użytkownik wyraźnie jej wymaga).
3.  **Brak danych = pominięcie:** Jeśli dokument nie wspomina o danej cesze, lub nie możesz jednoznacznie wywnioskować jej obecności (pewność < 80%), MUSISZ Pominąć ten klucz w wynikowym obiekcie JSON, lub ustawić na `null` (w zależności od wymogów biblioteki Pydantic, my używamy Optional[bool], więc bezpiecznie jest nie podawać klucza lub podać null, a my to odfiltrujemy). **Celem Reverse Search jest szukanie tylko tego, czego wprost wymaga klient. Nie dorysowuj cech, o które nie prosił.**
4.  **Enrichment (Rozpakowywanie Pakietów):**
    *   Jeśli klient wymaga np. "Pakiet Comfort", "Pakiet Zimowy", musisz wiedzieć co taki pakiet zazwyczaj zawiera (np. podgrzewane fotele, grzana kierownica) i zaznaczyć te konkretne cechy z naszej listy (np. `heated_front_seats: True`).
    *   Mapuj również synonimy rynkowe na nazwy z naszej ontologii (np. "Aktywny tempomat", "ACC", "Tempomat radarowy" -> `adaptive_cruise_control: True`).
5.  **Dedykowany Kontekst Reverse Search:** Pamiętaj, że analizujesz zapytanie *o* samochód. Szukamy wymagań minimalnych klienta (np. "Chcę auto z hakiem i automatem"). 

## KATEGORIE CECH (ONTOLOGIA FLOTOWA)

Oto pełna lista 202 obsługiwanych cech pogrupowana tematycznie:

**BEZPIECZEŃSTWO I ASYSTENCI JAZDY (ADAS)**
*   `adaptive_cruise_control` (Aktywny tempomat (ACC))
*   `cruise_control` (Tempomat (standardowy))
*   `blind_spot_monitor` (Asystent martwego pola (BLIS/BSM))
*   `lane_keeping_assist` (Asystent pasa ruchu (Lane Assist))
*   `front_assist` (Asystent hamowania awaryjnego (Front Assist))
*   `rear_cross_traffic_alert` (Asystent wyjazdu z miejsca parkingowego)
*   `traffic_sign_recognition` (Rozpoznawanie znaków drogowych)
*   `driver_fatigue_monitor` (System monitorowania zmęczenia kierowcy)
*   `parking_sensors_front` (Czujniki parkowania – przód)
*   `parking_sensors_rear` (Czujniki parkowania – tył)
*   `parking_sensors_360` (Czujniki parkowania 360)
*   `backup_camera` (Kamera cofania)
*   `camera_360` (Kamera 360 stopni / Area View)
*   `automated_parking_assist` (Asystent parkowania (Park Assist))
*   `hill_hold_assist` (Asystent ruszania pod górę (Hill Hold))
*   `hill_descent_control` (Asystent zjazdu ze wzniesienia)
*   `night_vision` (Asystent jazdy nocnej (Night Vision))
*   `hud_display` (Wyświetlacz Head-Up (HUD))
*   `isofix_rear` (System ISOFIX (tylna kanapa))
*   `isofix_front` (System ISOFIX (przedni fotel pasażera))
*   `airbags_front` (Poduszki powietrzne czołowe)
*   `airbags_side_front` (Poduszki powietrzne boczne – przód)
*   `airbags_side_rear` (Poduszki powietrzne boczne – tył)
*   `airbags_curtain` (Kurtyny powietrzne)
*   `airbag_knee_driver` (Poduszka kolanowa kierowcy)
*   `tpms_sensors` (System monitorowania ciśnienia w oponach)
*   `emergency_call` (System eCall)
*   `alarm_system` (Autoalarm)
*   `immobilizer` (Immobilizer)

**OŚWIETLENIE I WIDOCZNOŚĆ**
*   `led_headlights_basic` (Reflektory LED (Basic/Eco))
*   `led_headlights_matrix` (Reflektory Matrycowe (Matrix LED/Multibeam))
*   `halogen_headlights` (Reflektory halogenowe)
*   `laser_headlights` (Reflektory laserowe)
*   `automatic_high_beams` (Asystent świateł drogowych)
*   `led_daytime_lights` (Światła do jazdy dziennej LED)
*   `led_tail_lights` (Tylne światła LED)
*   `dynamic_turn_signals` (Dynamiczne kierunkowskazy)
*   `fog_lights` (Światła przeciwmgielne)
*   `cornering_lights` (Doświetlanie zakrętów)
*   `headlight_washers` (Spryskiwacze reflektorów)
*   `rain_sensor` (Czujnik deszczu)
*   `dusk_sensor` (Czujnik zmierzchu)
*   `auto_dimming_rearview_mirror` (Lusterko wsteczne elektrochromatyczne)
*   `heated_windshield` (Podgrzewana przednia szyba)
*   `heated_washer_nozzles` (Podgrzewane dysze spryskiwaczy)
*   `tinted_rear_windows` (Przyciemniane szyby tylne)
*   `soundproof_windows` (Szyby dźwiękoszczelne / akustyczne)

**KOMFORT I WNĘTRZE**
*   `auto_ac_1_zone` (Klimatyzacja automatyczna 1-strefowa)
*   `auto_ac_2_zones` (Klimatyzacja automatyczna 2-strefowa)
*   `auto_ac_3_zones` (Klimatyzacja automatyczna 3-strefowa)
*   `auto_ac_4_zones` (Klimatyzacja automatyczna 4-strefowa)
*   `manual_ac` (Klimatyzacja manualna)
*   `auxiliary_heating_webasto` (Ogrzewanie postojowe (Webasto))
*   `heated_front_seats` (Podgrzewane fotele przednie)
*   `heated_rear_seats` (Podgrzewane fotele tylne)
*   `ventilated_front_seats` (Wentylowane fotele przednie)
*   `massage_front_seats` (Fotele przednie z funkcją masażu)
*   `electric_driver_seat` (Elektrycznie sterowany fotel kierowcy)
*   `electric_passenger_seat` (Elektrycznie sterowany fotel pasażera)
*   `seat_memory` (Pamięć ustawień foteli)
*   `lumbar_support` (Regulacja podparcia lędźwiowego)
*   `sport_seats` (Sportowe fotele)
*   `leather_upholstery` (Skórzana tapicerka (nat./ekologiczna))
*   `alcantara_upholstery` (Tapicerka z Alcantary / zamszu)
*   `fabric_upholstery` (Materiałożowa tapicerka)
*   `leather_steering_wheel` (Skórzana kierownica)
*   `heated_steering_wheel` (Podgrzewana kierownica)
*   `multifunction_steering_wheel` (Kierownica wielofunkcyjna)
*   `paddle_shifters` (Łopatki do zmiany biegów przy kierownicy)
*   `keyless_entry_start` (System bezkluczykowy (Keyless Go/Access))
*   `keyless_start_only` (Odpalanie bezkluczykowe (tylko guzik))
*   `ambient_lighting` (Oświetlenie wnętrza Ambiente)
*   `panoramic_roof` (Szklany dach panoramiczny)
*   `sunroof` (Szyberdach (uchylny/otwierany))
*   `black_headliner` (Czarna podsufitka)
*   `front_armrest` (Podłokietnik z przodu)
*   `rear_armrest` (Podłokietnik z tyłu)
*   `rear_window_blinds` (Rolety szyb bocznych z tyłu)

**MULTIMEDIA I TECHNOLOGIA**
*   `digital_instrument_cluster` (Cyfrowe zegary (Virtual Cockpit))
*   `analog_instrument_cluster` (Analogowe zegary z wyświetlaczem środkowym)
*   `navigation_system` (System nawigacji satelitarnej)
*   `apple_carplay_android_auto` (Apple CarPlay / Android Auto (przewodowy))
*   `wireless_carplay_android_auto` (Bezprzewodowy Apple CarPlay / Android Auto)
*   `bluetooth` (Zestaw głośnomówiący Bluetooth)
*   `wireless_phone_charger` (Indukcyjna ładowarka do telefonu)
*   `premium_audio_system` (System nagłośnienia Premium (np. Bose, Harman Kardon))
*   `dab_radio` (Radio cyfrowe DAB+)
*   `usb_c_ports_front` (Porty USB-C z przodu)
*   `usb_c_ports_rear` (Porty USB-C z tyłu)
*   `voice_control` (System obsługi głosowej)
*   `touchscreen_display` (Ekran dotykowy systemu multimedialnego)
*   `rear_seat_entertainment` (Ekrany multimedialne dla pasażerów z tyłu)
*   `wifi_hotspot` (Wbudowany moduł Wi-Fi / Hotspot)

**NADWOZIE I ZEWNĘTRZE**
*   `alloy_wheels_16` (Felgi aluminiowe 16")
*   `alloy_wheels_17` (Felgi aluminiowe 17")
*   `alloy_wheels_18` (Felgi aluminiowe 18")
*   `alloy_wheels_19` (Felgi aluminiowe 19")
*   `alloy_wheels_20_plus` (Felgi aluminiowe 20" i większe)
*   `steel_wheels` (Felgi stalowe)
*   `metallic_paint` (Lakier metalizowany)
*   `pearl_paint` (Lakier perłowy)
*   `matte_paint` (Lakier matowy)
*   `solid_paint` (Lakier niemetalizowany (akrylowy))
*   `two_tone_paint` (Lakier dwukolorowy (czarny dach itp.))
*   `roof_rails` (Relingi dachowe)
*   `tow_bar_retractable` (Hak holowniczy składany / elektryczny)
*   `tow_bar_fixed` (Hak holowniczy stały / demontowalny)
*   `tow_bar_prep` (Pre-instalacja pod hak holowniczy)
*   `electric_tailgate` (Elektrycznie otwierana klapa bagażnika)
*   `hands_free_tailgate` (Bezdotykowe otwieranie bagażnika (gestem stopy))
*   `folding_side_mirrors` (Częściowo lub w pełni składane lusterka boczne)
*   `heated_side_mirrors` (Podgrzewane lusterka boczne)
*   `electric_side_mirrors` (Elektrycznie regulowane lusterka)

**DYNAMIKA I ZAWIESZENIE**
*   `adaptive_suspension` (Zawieszenie adaptacyjne (DCC))
*   `air_suspension` (Zawieszenie pneumatyczne)
*   `sport_suspension` (Zawieszenie sportowe (obniżone))
*   `drive_mode_select` (Wybór profilu jazdy (Drive Mode))
*   `sport_exhaust` (Sportowy układ wydechowy)
*   `mechanical_lsd` (Mechaniczny mechanizm różnicowy o ograniczonym poślizgu (szpera))
*   `rear_wheel_steering` (Skrętna tylna oś)
*   `ceramic_brakes` (Hamulce ceramiczne)
*   `launch_control` (System Launch Control)
*   `offroad_mode` (Tryb jazdy Off-Road)

**POJAZDY ELEKTRYCZNE I HYBRYDY (EV / PHEV)**
*   `heat_pump` (Pompa ciepła)
*   `ac_charger_11kw` (Ładowarka pokładowa AC 11 kW)
*   `ac_charger_22kw` (Ładowarka pokładowa AC 22 kW)
*   `dc_fast_charging` (Możliwość szybkiego ładowania DC)
*   `charging_cable_type2` (Kabel do ładowania Type 2 (AC))
*   `charging_cable_230v` (Kabel do ładowania z gniazdka 230V)
*   `battery_preconditioning` (System kondycjonowania baterii przed ładowaniem)
*   `v2l_vehicle_to_load` (Funkcja zasilania urządzeń z auta (V2L))
*   `acoustic_vehicle_alerting` (System AVAS (dźwięk przy niskich prędkościach))

**--- ZUPEŁNIE NOWE CECHY (TYLKO DLA LCV/DOSTAWCZYCH) ---**
_Te cechy stosuj wyłącznie przy analizie zapytania o pojazdy typu furgon, bus, podwozie, pickup itp._

**BUDOWA I DRZWI (LCV)**
*   `sliding_door_right` (Drzwi przesuwne boczne - prawa strona)
*   `sliding_door_left` (Drzwi przesuwne boczne - lewa strona)
*   `sliding_doors_both` (Drzwi przesuwne - obie strony)
*   `rear_doors_180` (Tylne drzwi dwuskrzydłowe otwierane do 180 stopni)
*   `rear_doors_270` (Tylne drzwi dwuskrzydłowe otwierane do 270 stopni)
*   `tailgate_rear` (Tylna klapa podnoszona do góry)
*   `glazed_rear_doors` (Przeszklone drzwi tylne)
*   `glazed_sliding_doors` (Przeszklone drzwi przesuwne)
*   `bulkhead_full_solid` (Pełna stalowa ściana grodziowa bez okna)
*   `bulkhead_with_window` (Ściana grodziowa z oknem)
*   `bulkhead_mesh` (Ściana grodziowa z siatki / kraty)
*   `cargo_floor_wood` (Drewniana podłoga w przestrzeni ładunkowej)
*   `cargo_floor_plastic` (Wykładzina antypoślizgowa z tworzywa)
*   `cargo_wall_protection_wood` (Wyłożenie boków (ścian) sklejką)
*   `cargo_wall_protection_plastic` (Wyłożenie boków płytą z tworzywa sztucznego)
*   `led_cargo_lighting` (Oświetlenie LED przestrzeni ładunkowej)
*   `roof_rack_bars` (Bagażnik dachowy / poprzeczki zintegrowane)

**MODYFIKACJE I UŻYTKOWOŚĆ (LCV)**
*   `reinforced_suspension` (Wzmocnione zawieszenie)
*   `payload_increased` (Powiększona ładowność)
*   `power_take_off_pto` (Przygotowanie pod przystawkę odbioru mocy (PTO))
*   `second_battery` (Dodatkowy akumulator)
*   `alternator_heavy_duty` (Wzmocniony alternator)
*   `tachograph_digital` (Tachograf cyfrowy)
*   `speed_limiter_90` (Ogranicznik prędkości 90 km/h)
*   `all_weather_tires` (Opony wielosezonowe / całoroczne)
*   `winch` (Wyciągarka)
*   `cargo_rails` (Szyny mocujące w przestrzeni ładunkowej)

**ZABUDOWY SPECJALISTYCZNE I PRZYGOTOWANIA (LCV)**
*   `box_body_kontener` (Zabudowa: Kontener)
*   `freezer_body_chlodnia` (Zabudowa: Chłodnia)
*   `isotherm_body_izoterma` (Zabudowa: Izoterma)
*   `dropside_body_skrzynia` (Zabudowa: Skrzynia otwarta)
*   `pickup_bed_paka` (Zabudowa: Paka (Pickup) / Otwarta przestrzeń ładunkowa)
*   `tarpaulin_body_plandeka` (Zabudowa: Skrzynia z plandeką)
*   `tipper_body_wywrotka` (Zabudowa: Wywrotka (1-W lub 3-W))
*   `crew_cab_brygadowka` (Zabudowa: Brygadowa (Mixto/Crew Cab))
*   `crane_hds` (Zabudowa: Żuraw (HDS))
*   `liftgate_winda` (Winda załadowcza (Dhollandia, Bär itp.))
*   `cooling_unit_agregat` (Agregat chłodniczy (Carrier, Thermo King))
*   `sleeping_cabin` (Kabina sypialna (Kurnik / Spojkar itp.))
*   `air_suspension_bellows` (Poduszki pneumatyczne zawieszenia (dokładane))

**KOMFORT KIEROWCY LCV**
*   `suspended_driver_seat` (Amortyzowany fotel kierowcy)
*   `double_passenger_bench` (Podwójna ławka pasażera z przodu (auto 3-osobowe))
*   `single_passenger_seat` (Pojedynczy fotel pasażera (auto 2-osobowe))
*   `passenger_bench_folding_table` (Składany stolik w oparciu ławki pasażera)
*   `under_seat_storage` (Schowek pod siedziskiem pasażera)
*   `overhead_storage` (Półka nad przednią szybą (kapelusznik))
*   `heating_webasto_air_LCV` (Ogrzewanie postojowe powietrzne układu ładunkowego/sypialni)
"""


class ExtractedReverseSearchFeatures(BaseModel):
    # BEZPIECZEŃSTWO I ASYSTENCI JAZDY (ADAS)
    adaptive_cruise_control: Optional[bool] = Field(None)
    cruise_control: Optional[bool] = Field(None)
    blind_spot_monitor: Optional[bool] = Field(None)
    lane_keeping_assist: Optional[bool] = Field(None)
    front_assist: Optional[bool] = Field(None)
    rear_cross_traffic_alert: Optional[bool] = Field(None)
    traffic_sign_recognition: Optional[bool] = Field(None)
    driver_fatigue_monitor: Optional[bool] = Field(None)
    parking_sensors_front: Optional[bool] = Field(None)
    parking_sensors_rear: Optional[bool] = Field(None)
    parking_sensors_360: Optional[bool] = Field(None)
    backup_camera: Optional[bool] = Field(None)
    camera_360: Optional[bool] = Field(None)
    automated_parking_assist: Optional[bool] = Field(None)
    hill_hold_assist: Optional[bool] = Field(None)
    hill_descent_control: Optional[bool] = Field(None)
    night_vision: Optional[bool] = Field(None)
    hud_display: Optional[bool] = Field(None)
    isofix_rear: Optional[bool] = Field(None)
    isofix_front: Optional[bool] = Field(None)
    airbags_front: Optional[bool] = Field(None)
    airbags_side_front: Optional[bool] = Field(None)
    airbags_side_rear: Optional[bool] = Field(None)
    airbags_curtain: Optional[bool] = Field(None)
    airbag_knee_driver: Optional[bool] = Field(None)
    tpms_sensors: Optional[bool] = Field(None)
    emergency_call: Optional[bool] = Field(None)
    alarm_system: Optional[bool] = Field(None)
    immobilizer: Optional[bool] = Field(None)

    # OŚWIETLENIE I WIDOCZNOŚĆ
    led_headlights_basic: Optional[bool] = Field(None)
    led_headlights_matrix: Optional[bool] = Field(None)
    halogen_headlights: Optional[bool] = Field(None)
    laser_headlights: Optional[bool] = Field(None)
    automatic_high_beams: Optional[bool] = Field(None)
    led_daytime_lights: Optional[bool] = Field(None)
    led_tail_lights: Optional[bool] = Field(None)
    dynamic_turn_signals: Optional[bool] = Field(None)
    fog_lights: Optional[bool] = Field(None)
    cornering_lights: Optional[bool] = Field(None)
    headlight_washers: Optional[bool] = Field(None)
    rain_sensor: Optional[bool] = Field(None)
    dusk_sensor: Optional[bool] = Field(None)
    auto_dimming_rearview_mirror: Optional[bool] = Field(None)
    heated_windshield: Optional[bool] = Field(None)
    heated_washer_nozzles: Optional[bool] = Field(None)
    tinted_rear_windows: Optional[bool] = Field(None)
    soundproof_windows: Optional[bool] = Field(None)

    # KOMFORT I WNĘTRZE
    auto_ac_1_zone: Optional[bool] = Field(None)
    auto_ac_2_zones: Optional[bool] = Field(None)
    auto_ac_3_zones: Optional[bool] = Field(None)
    auto_ac_4_zones: Optional[bool] = Field(None)
    manual_ac: Optional[bool] = Field(None)
    auxiliary_heating_webasto: Optional[bool] = Field(None)
    heated_front_seats: Optional[bool] = Field(None)
    heated_rear_seats: Optional[bool] = Field(None)
    ventilated_front_seats: Optional[bool] = Field(None)
    massage_front_seats: Optional[bool] = Field(None)
    electric_driver_seat: Optional[bool] = Field(None)
    electric_passenger_seat: Optional[bool] = Field(None)
    seat_memory: Optional[bool] = Field(None)
    lumbar_support: Optional[bool] = Field(None)
    sport_seats: Optional[bool] = Field(None)
    leather_upholstery: Optional[bool] = Field(None)
    alcantara_upholstery: Optional[bool] = Field(None)
    fabric_upholstery: Optional[bool] = Field(None)
    leather_steering_wheel: Optional[bool] = Field(None)
    heated_steering_wheel: Optional[bool] = Field(None)
    multifunction_steering_wheel: Optional[bool] = Field(None)
    paddle_shifters: Optional[bool] = Field(None)
    keyless_entry_start: Optional[bool] = Field(None)
    keyless_start_only: Optional[bool] = Field(None)
    ambient_lighting: Optional[bool] = Field(None)
    panoramic_roof: Optional[bool] = Field(None)
    sunroof: Optional[bool] = Field(None)
    black_headliner: Optional[bool] = Field(None)
    front_armrest: Optional[bool] = Field(None)
    rear_armrest: Optional[bool] = Field(None)
    rear_window_blinds: Optional[bool] = Field(None)

    # MULTIMEDIA I TECHNOLOGIA
    digital_instrument_cluster: Optional[bool] = Field(None)
    analog_instrument_cluster: Optional[bool] = Field(None)
    navigation_system: Optional[bool] = Field(None)
    apple_carplay_android_auto: Optional[bool] = Field(None)
    wireless_carplay_android_auto: Optional[bool] = Field(None)
    bluetooth: Optional[bool] = Field(None)
    wireless_phone_charger: Optional[bool] = Field(None)
    premium_audio_system: Optional[bool] = Field(None)
    dab_radio: Optional[bool] = Field(None)
    usb_c_ports_front: Optional[bool] = Field(None)
    usb_c_ports_rear: Optional[bool] = Field(None)
    voice_control: Optional[bool] = Field(None)
    touchscreen_display: Optional[bool] = Field(None)
    rear_seat_entertainment: Optional[bool] = Field(None)
    wifi_hotspot: Optional[bool] = Field(None)

    # NADWOZIE I ZEWNĘTRZE
    alloy_wheels_16: Optional[bool] = Field(None)
    alloy_wheels_17: Optional[bool] = Field(None)
    alloy_wheels_18: Optional[bool] = Field(None)
    alloy_wheels_19: Optional[bool] = Field(None)
    alloy_wheels_20_plus: Optional[bool] = Field(None)
    steel_wheels: Optional[bool] = Field(None)
    metallic_paint: Optional[bool] = Field(None)
    pearl_paint: Optional[bool] = Field(None)
    matte_paint: Optional[bool] = Field(None)
    solid_paint: Optional[bool] = Field(None)
    two_tone_paint: Optional[bool] = Field(None)
    roof_rails: Optional[bool] = Field(None)
    tow_bar_retractable: Optional[bool] = Field(None)
    tow_bar_fixed: Optional[bool] = Field(None)
    tow_bar_prep: Optional[bool] = Field(None)
    electric_tailgate: Optional[bool] = Field(None)
    hands_free_tailgate: Optional[bool] = Field(None)
    folding_side_mirrors: Optional[bool] = Field(None)
    heated_side_mirrors: Optional[bool] = Field(None)
    electric_side_mirrors: Optional[bool] = Field(None)

    # DYNAMIKA I ZAWIESZENIE
    adaptive_suspension: Optional[bool] = Field(None)
    air_suspension: Optional[bool] = Field(None)
    sport_suspension: Optional[bool] = Field(None)
    drive_mode_select: Optional[bool] = Field(None)
    sport_exhaust: Optional[bool] = Field(None)
    mechanical_lsd: Optional[bool] = Field(None)
    rear_wheel_steering: Optional[bool] = Field(None)
    ceramic_brakes: Optional[bool] = Field(None)
    launch_control: Optional[bool] = Field(None)
    offroad_mode: Optional[bool] = Field(None)

    # POJAZDY ELEKTRYCZNE I HYBRYDY (EV / PHEV)
    heat_pump: Optional[bool] = Field(None)
    ac_charger_11kw: Optional[bool] = Field(None)
    ac_charger_22kw: Optional[bool] = Field(None)
    dc_fast_charging: Optional[bool] = Field(None)
    charging_cable_type2: Optional[bool] = Field(None)
    charging_cable_230v: Optional[bool] = Field(None)
    battery_preconditioning: Optional[bool] = Field(None)
    v2l_vehicle_to_load: Optional[bool] = Field(None)
    acoustic_vehicle_alerting: Optional[bool] = Field(None)

    # ZUPEŁNIE NOWE CECHY (TYLKO DLA LCV/DOSTAWCZYCH)
    sliding_door_right: Optional[bool] = Field(None)
    sliding_door_left: Optional[bool] = Field(None)
    sliding_doors_both: Optional[bool] = Field(None)
    rear_doors_180: Optional[bool] = Field(None)
    rear_doors_270: Optional[bool] = Field(None)
    tailgate_rear: Optional[bool] = Field(None)
    glazed_rear_doors: Optional[bool] = Field(None)
    glazed_sliding_doors: Optional[bool] = Field(None)
    bulkhead_full_solid: Optional[bool] = Field(None)
    bulkhead_with_window: Optional[bool] = Field(None)
    bulkhead_mesh: Optional[bool] = Field(None)
    cargo_floor_wood: Optional[bool] = Field(None)
    cargo_floor_plastic: Optional[bool] = Field(None)
    cargo_wall_protection_wood: Optional[bool] = Field(None)
    cargo_wall_protection_plastic: Optional[bool] = Field(None)
    led_cargo_lighting: Optional[bool] = Field(None)
    roof_rack_bars: Optional[bool] = Field(None)

    reinforced_suspension: Optional[bool] = Field(None)
    payload_increased: Optional[bool] = Field(None)
    power_take_off_pto: Optional[bool] = Field(None)
    second_battery: Optional[bool] = Field(None)
    alternator_heavy_duty: Optional[bool] = Field(None)
    tachograph_digital: Optional[bool] = Field(None)
    speed_limiter_90: Optional[bool] = Field(None)
    all_weather_tires: Optional[bool] = Field(None)
    winch: Optional[bool] = Field(None)
    cargo_rails: Optional[bool] = Field(None)

    box_body_kontener: Optional[bool] = Field(None)
    freezer_body_chlodnia: Optional[bool] = Field(None)
    isotherm_body_izoterma: Optional[bool] = Field(None)
    dropside_body_skrzynia: Optional[bool] = Field(None)
    pickup_bed_paka: Optional[bool] = Field(None)
    tarpaulin_body_plandeka: Optional[bool] = Field(None)
    tipper_body_wywrotka: Optional[bool] = Field(None)
    crew_cab_brygadowka: Optional[bool] = Field(None)
    crane_hds: Optional[bool] = Field(None)
    liftgate_winda: Optional[bool] = Field(None)
    cooling_unit_agregat: Optional[bool] = Field(None)
    sleeping_cabin: Optional[bool] = Field(None)
    air_suspension_bellows: Optional[bool] = Field(None)

    suspended_driver_seat: Optional[bool] = Field(None)
    double_passenger_bench: Optional[bool] = Field(None)
    single_passenger_seat: Optional[bool] = Field(None)
    passenger_bench_folding_table: Optional[bool] = Field(None)
    under_seat_storage: Optional[bool] = Field(None)
    overhead_storage: Optional[bool] = Field(None)
    heating_webasto_air_LCV: Optional[bool] = Field(None)
