import json


def to_sql_val(val, is_str=False, is_bool=False, is_numeric=False):
    if val is None or val == "" or val == "NULL":
        return "NULL"
    val = str(val).replace("'", "''")
    if is_bool:
        return "TRUE" if val in ("1", "true", "True") else "FALSE"
    if is_numeric:
        return val.replace(",", ".")  # handle Polish decimal format if needed
    if is_str:
        return f"'{val}'"
    return val


def generate():
    with open("service_insurance_data.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    # Output file
    out_file = "supabase/migrations/20260224230000_add_smart_service_and_insurance.sql"

    with open(out_file, "w", encoding="utf-8") as f:
        f.write("-- Migration: Smart Service and Insurance Tables\n\n")

        # ------------------------------------------------------------------
        # 1. NEW SMART SERVICE TABLES
        # ------------------------------------------------------------------

        # A) service_rates_config (Stawki za KM)
        f.write("-- 1. Smart Service Rates (per km)\n")
        f.write("CREATE TABLE public.service_rates_config (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    klasa_id BIGINT NOT NULL,\n")
        f.write("    rodzaj_paliwa TEXT NOT NULL,\n")
        f.write("    stawka_za_km NUMERIC(10,2) NOT NULL DEFAULT 0.00,\n")
        f.write(
            "    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL\n"
        )
        f.write(");\n\n")

        f.write("ALTER TABLE public.service_rates_config ENABLE ROW LEVEL SECURITY;\n")
        f.write(
            'CREATE POLICY "Allow public read access for service_rates_config" ON public.service_rates_config FOR SELECT USING (true);\n'
        )
        f.write(
            'CREATE POLICY "Allow public update access for service_rates_config" ON public.service_rates_config FOR UPDATE USING (true);\n'
        )
        f.write(
            'CREATE POLICY "Allow public insert access for service_rates_config" ON public.service_rates_config FOR INSERT WITH CHECK (true);\n'
        )
        f.write(
            'CREATE POLICY "Allow public delete access for service_rates_config" ON public.service_rates_config FOR DELETE USING (true);\n\n'
        )

        # Initial Mock Data for service_rates_config (to be edited by user later in UI)
        # Fuel types in V1: "Benzyna", "Diesel", "Elektryczny", "Hybryda", "Hybryda Plug-in", "LPG"
        f.write("-- Seed some mock initial data for service_rates_config\n")
        f.write(
            "INSERT INTO public.service_rates_config (klasa_id, rodzaj_paliwa, stawka_za_km) VALUES\n"
        )
        f.write("(3, 'Benzyna', 0.12),\n")  # Klasa B (ID 3 in standard LTR)
        f.write("(3, 'Diesel', 0.14),\n")
        f.write("(4, 'Benzyna', 0.14),\n")  # Klasa C
        f.write("(4, 'Diesel', 0.16),\n")
        f.write("(5, 'Benzyna', 0.16),\n")  # Klasa D
        f.write("(5, 'Diesel', 0.18);\n\n")

        # B) service_base_costs_config (Koszty Przeglądów Podstawowych)
        f.write("-- 2. Smart Service Base Costs (Yearly Minimum)\n")
        f.write("CREATE TABLE public.service_base_costs_config (\n")
        f.write("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    klasa_id BIGINT NOT NULL UNIQUE,\n")  # One base cost per class
        f.write(
            "    koszt_przegladu_podstawowego NUMERIC(10,2) NOT NULL DEFAULT 0.00,\n"
        )
        f.write(
            "    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL\n"
        )
        f.write(");\n\n")

        f.write(
            "ALTER TABLE public.service_base_costs_config ENABLE ROW LEVEL SECURITY;\n"
        )
        f.write(
            'CREATE POLICY "Allow public read access for service_base_costs_config" ON public.service_base_costs_config FOR SELECT USING (true);\n'
        )
        f.write(
            'CREATE POLICY "Allow public update access for service_base_costs_config" ON public.service_base_costs_config FOR UPDATE USING (true);\n'
        )
        f.write(
            'CREATE POLICY "Allow public insert access for service_base_costs_config" ON public.service_base_costs_config FOR INSERT WITH CHECK (true);\n'
        )
        f.write(
            'CREATE POLICY "Allow public delete access for service_base_costs_config" ON public.service_base_costs_config FOR DELETE USING (true);\n\n'
        )

        f.write("-- Seed some mock initial data for service_base_costs_config\n")
        f.write(
            "INSERT INTO public.service_base_costs_config (klasa_id, koszt_przegladu_podstawowego) VALUES\n"
        )
        f.write("(3, 1200.00),\n")  # Klasa B
        f.write("(4, 1500.00),\n")  # Klasa C
        f.write("(5, 1800.00);\n\n")  # Klasa D

        # ------------------------------------------------------------------
        # 2. MIGRATED LEGACY TABLES (Insurance, Replacement)
        # ------------------------------------------------------------------

        # LTRAdminUbezpieczenies -> ltr_admin_ubezpieczenia
        f.write("-- 3. Extracted Legacy Insurance Rates\n")
        f.write("CREATE TABLE public.ltr_admin_ubezpieczenia (\n")
        f.write("    id BIGINT PRIMARY KEY,\n")
        f.write("    kolejny_rok INT,\n")
        f.write("    stawka_bazowa_ac NUMERIC(10,2),\n")
        f.write("    skladka_oc_wartosc NUMERIC(10,2),\n")
        f.write("    klasa_id BIGINT\n")
        f.write(");\n\n")

        f.write(
            "ALTER TABLE public.ltr_admin_ubezpieczenia ENABLE ROW LEVEL SECURITY;\n"
        )
        f.write(
            'CREATE POLICY "Allow public read access for ltr_admin_ubezpieczenia" ON public.ltr_admin_ubezpieczenia FOR SELECT USING (true);\n\n'
        )

        rows_ubezpieczenia = data.get("LTRAdminUbezpieczenies", [])
        if rows_ubezpieczenia:
            f.write(
                "INSERT INTO public.ltr_admin_ubezpieczenia (id, kolejny_rok, stawka_bazowa_ac, skladka_oc_wartosc, klasa_id) VALUES\n"
            )
            values = []
            for r in rows_ubezpieczenia:
                v = f"({to_sql_val(r.get('Id'))}, {to_sql_val(r.get('KolejnyRok'))}, {to_sql_val(r.get('StawkaBazowaAC'), is_numeric=True)}, {to_sql_val(r.get('SkladkaOC_Wartosc'), is_numeric=True)}, {to_sql_val(r.get('KlasaId'))})"
                values.append(v)
            f.write(",\n".join(values) + ";\n\n")

        # LTRAdminStawkaZastepczies -> ltr_admin_stawka_zastepcza
        f.write("-- 4. Extracted Legacy Replacement Car Rates\n")
        f.write("CREATE TABLE public.ltr_admin_stawka_zastepcza (\n")
        f.write("    id BIGINT PRIMARY KEY,\n")
        f.write("    srednia_ilosc_dob_w_roku INT,\n")
        f.write("    doba_netto_wartosc NUMERIC(10,2),\n")
        f.write("    klasa_id BIGINT\n")
        f.write(");\n\n")

        f.write(
            "ALTER TABLE public.ltr_admin_stawka_zastepcza ENABLE ROW LEVEL SECURITY;\n"
        )
        f.write(
            'CREATE POLICY "Allow public read access for ltr_admin_stawka_zastepcza" ON public.ltr_admin_stawka_zastepcza FOR SELECT USING (true);\n\n'
        )

        rows_zastepcze = data.get("LTRAdminStawkaZastepczies", [])
        if rows_zastepcze:
            f.write(
                "INSERT INTO public.ltr_admin_stawka_zastepcza (id, srednia_ilosc_dob_w_roku, doba_netto_wartosc, klasa_id) VALUES\n"
            )
            values = []
            for r in rows_zastepcze:
                v = f"({to_sql_val(r.get('Id'))}, {to_sql_val(r.get('SredniaIloscDobWRoku'))}, {to_sql_val(r.get('DobaNetto_Wartosc'), is_numeric=True)}, {to_sql_val(r.get('KlasaId'))})"
                values.append(v)
            f.write(",\n".join(values) + ";\n\n")


if __name__ == "__main__":
    generate()
