CREATE TABLE public.rabaty (
    id bigint generated by default as identity primary key,
    kalkulacja text,
    lp integer,
    model text,
    wyposazenie text,
    ilosc integer,
    numer_oferty text,
    nr_kalkulacji text,
    uwagi text,
    kontrakt text
);

ALTER TABLE public.rabaty ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.rabaty FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.rabaty FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.rabaty FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.rabaty FOR DELETE USING (true);
