-- Skrypt do utworzenia tabeli engines w bazie Supabase
DROP TABLE IF EXISTS engines;

CREATE TABLE engines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT
);

-- Dodanie wpisów domyślnych
INSERT INTO engines (name, category, description) VALUES
('Benzyna (PB)', 'Konwencjonalne (ICE)', 'Czyste silniki benzynowe bez układów hybrydowych.'),
('Diesel (ON)', 'Konwencjonalne (ICE)', 'Klasyczne silniki wysokoprężne.'),
('Benzyna mHEV (PB-mHEV)', 'Miękkie Hybrydy (mHEV)', 'Silniki spalinowe benzynowe z drobnym elektrycznym wspomaganiem.'),
('Diesel mHEV (ON-mHEV)', 'Miękkie Hybrydy (mHEV)', 'Silniki spalinowe diesla z elektrycznym wspomaganiem.'),
('Hybryda (HEV)', 'Napędy Alternatywne (Zelektryfikowane)', 'Klasyczna hybryda (pełna, samoładująca). Najpopularniejszy napęd alternatywny w Polsce.'),
('Hybryda Plug-in (PHEV)', 'Napędy Alternatywne (Zelektryfikowane)', 'Hybryda ładowana z gniazdka.'),
('Elektryczny (BEV)', 'Napędy Alternatywne (Zelektryfikowane)', 'Pojazdy w pełni elektryczne (Battery Electric Vehicle).'),
('Wodór (FCEV)', 'Napędy Alternatywne (Zelektryfikowane)', 'Pojazdy na ogniwa paliwowe, statystycznie ok. 0% udziału w rynku.'),
('Autogaz (LPG)', 'Napędy Alternatywne (Zelektryfikowane)', 'Instalacje zasilane gazem płynnym (LPG), często fabryczne.');
