DROP TABLE IF EXISTS public.rabaty;
DROP TABLE IF EXISTS public.tabela_rabaty;

CREATE TABLE public.tabela_rabaty (
    id bigint generated by default as identity primary key,
    marka text,
    model text,
    kod text,
    wykluczenia text,
    rabat double precision
);

ALTER TABLE public.tabela_rabaty ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.tabela_rabaty FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.tabela_rabaty FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.tabela_rabaty FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.tabela_rabaty FOR DELETE USING (true);
