import os
import pandas as pd
from sqlalchemy import create_engine
import json

MAPPING = {
    "1.csv": "LTRAdminParametry_czak",
    "2.csv": "CennikOpon_czak",
    "3.csv": "LTRAdminOplatyTransportowe_czak",
    "4.csv": "LTRAdminGSM_czak",
    "5.csv": "TabelaSerwisowa_czak",
    "6.csv": "LTRAdminKosztySerwisowe_czak",
    "7.csv": "LTRAdminStawkaZastepczy_czak",
    "8.csv": "KlasaSAMAR_czak",
    "9.csv": "LTRAdminTabelaWRKlasa_czak",
    "10.csv": "LTRAdminTabelaWRDeprecjacja_czak",
    "11.csv": "LTRAdminTabelaWRPrzebieg_czak",
    "12.csv": "LTRAdminTabelaWRDoposazenie_czak",
    "13.csv": "LTRAdminKorektaWRKolor_czak",
    "14.csv": "LTRAdminKorektaWRZabudowa_czak",
    "15.csv": "LTRAdminKorektaWRRocznik_czak",
    "16.csv": "LTRAdminKorektaWRMarka_czak",
    "17.csv": "LTRAdminUbezpieczenie_czak",
    "18.csv": "LTRAdminWspolczynnikiSzkodowe_czak",
    "19.csv": "RodzajPaliwa_czak",
    "20.csv": "LTRPrzebiegNormatywny_czak",
}


def clean_column_name(name):
    # Remove special characters from column names to safely use them in Postgres
    return str(name).strip().replace(" ", "_").replace(".", "_").replace("-", "_")


def main():
    directory = r"C:\Users\proma\Downloads\tabeleRMS"
    engine = create_engine("postgresql://postgres:postgres@127.0.0.1:54322/postgres")

    schema_data = {}

    for file_name, table_name in MAPPING.items():
        file_path = os.path.join(directory, file_name)
        if not os.path.exists(file_path):
            print(f"File not found: {file_path}")
            continue

        print(f"Importing {file_name} as {table_name}...")

        try:
            df = pd.read_csv(
                file_path, sep=";", decimal=",", encoding="utf-8-sig", header=None
            )
        except UnicodeDecodeError:
            print("UTF-8 failed, trying cp1250...")
            df = pd.read_csv(
                file_path, sep=";", decimal=",", encoding="cp1250", header=None
            )

        df.columns = [f"col_{i}" for i in range(len(df.columns))]

        # Save to postgres
        df.to_sql(table_name, engine, if_exists="replace", index=False)

        # Prepare for TS schema
        columns_info = []
        for col, dtype in df.dtypes.items():
            dt_str = str(dtype)
            if "int" in dt_str:
                ts_type = "number"
            elif "float" in dt_str:
                ts_type = "number"
            elif "bool" in dt_str:
                ts_type = "boolean"
            else:
                ts_type = "string"

            columns_info.append({"name": col, "type": ts_type})

        schema_data[table_name] = columns_info
        print(f"Successfully imported {table_name} with {len(df)} rows.")

    # Generate TypeScript file
    ts_content = f"// This file is auto-generated by import_rms.py\n\nexport const RMSTablesSchema = {json.dumps(schema_data, indent=2)};\n"

    frontend_dir = r"d:\kalk_v3\frontend\src\RmsCrud"
    os.makedirs(frontend_dir, exist_ok=True)

    ts_path = os.path.join(frontend_dir, "rms_schema.ts")
    with open(ts_path, "w", encoding="utf-8") as f:
        f.write(ts_content)

    print(f"Created TS schema at {ts_path}")


if __name__ == "__main__":
    main()
