// Static lists sourced from DB (samar_classes & engines tables) - updated: 2026-03-18

export const ALL_SAMAR_CLASSES: string[] = [
  "Autobusy - AUTOBUSY",
  "Ciężkie dostawcze - CIĘŻKIE DOSTAWCZE",
  "Kombivany - H KOMBI-VANY",
  "Lekkie dostawcze - KOMBI VAN",
  "Lekkie dostawcze - VAN",
  "Minibusy - I MINIBUSY",
  "Pick-up - PICK-UP",
  "Podstawowa - A MINI",
  "Podstawowa - B MAŁE",
  "Podstawowa - C NIŻSZA ŚREDNIA",
  "Podstawowa - D ŚREDNIA",
  "Podstawowa - E WYŻSZA",
  "Podstawowa - F LUKSUSOWE",
  "Podstawowa - G SUPER LUKSUSOWE",
  "Sportowo-rekreacyjne - A MINI",
  "Sportowo-rekreacyjne - B MAŁE",
  "Sportowo-rekreacyjne - C NIŻSZA ŚREDNIA",
  "Sportowo-rekreacyjne - D ŚREDNIA",
  "Sportowo-rekreacyjne - E WYŻSZA",
  "Sportowo-rekreacyjne - F LUKSUSOWE",
  "Sportowo-rekreacyjne - G SUPER LUKSUSOWE",
  "Średnie dostawcze - ŚREDNIE DOSTAWCZE",
  "Terenowo-rekreacyjne (SUV) - B MAŁE",
  "Terenowo-rekreacyjne (SUV) - C NIŻSZA ŚREDNIA",
  "Terenowo-rekreacyjne (SUV) - D ŚREDNIA",
  "Terenowo-rekreacyjne (SUV) - E WYŻSZA",
  "Terenowo-rekreacyjne (SUV) - F LUKSUSOWE",
  "Terenowo-rekreacyjne (SUV) - G SUPER LUKSUSOWE",
  "Vany - B MICROVANY",
  "Vany - C MINIVANY",
  "Vany - D VANY",
  "Vany - E WYŻSZA",
  "Vany - F LUKSUSOWE",
];

export const ALL_ENGINE_TYPES: string[] = [
  "Benzyna (PB)",
  "Benzyna mHEV (PB-mHEV)",
  "Diesel (ON)",
  "Diesel mHEV (ON-mHEV)",
  "Elektryczny (BEV)",
  "Hybryda (HEV)",
  "LPG",
  "Plug-in Hybrid (PHEV)",
  "Wodór (FCEV)",
];
