// This file is auto-generated by import_rms.py

export const RMSTablesSchema = {
  "LTRAdminParametry_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "string"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "string"
    }
  ],
  "CennikOpon_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "number"
    },
    {
      "name": "col_3",
      "type": "number"
    },
    {
      "name": "col_4",
      "type": "string"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "string"
    }
  ],
  "LTRAdminOplatyTransportowe_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "number"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "string"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "string"
    }
  ],
  "LTRAdminGSM_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "number"
    },
    {
      "name": "col_4",
      "type": "number"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "string"
    }
  ],
  "TabelaSerwisowa_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "number"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "number"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "string"
    },
    {
      "name": "col_10",
      "type": "string"
    },
    {
      "name": "col_11",
      "type": "string"
    }
  ],
  "LTRAdminKosztySerwisowe_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "number"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "string"
    },
    {
      "name": "col_5",
      "type": "string"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "number"
    },
    {
      "name": "col_10",
      "type": "string"
    },
    {
      "name": "col_11",
      "type": "number"
    }
  ],
  "LTRAdminStawkaZastepczy_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "string"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "string"
    },
    {
      "name": "col_10",
      "type": "number"
    }
  ],
  "KlasaSAMAR_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "number"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "string"
    },
    {
      "name": "col_9",
      "type": "number"
    }
  ],
  "LTRAdminTabelaWRKlasa_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "number"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "number"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "number"
    }
  ],
  "LTRAdminTabelaWRDeprecjacja_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "number"
    },
    {
      "name": "col_2",
      "type": "number"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "string"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "number"
    },
    {
      "name": "col_10",
      "type": "number"
    }
  ],
  "LTRAdminTabelaWRPrzebieg_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "number"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "number"
    }
  ],
  "LTRAdminTabelaWRDoposazenie_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "number"
    },
    {
      "name": "col_2",
      "type": "number"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "string"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "number"
    },
    {
      "name": "col_10",
      "type": "number"
    }
  ],
  "LTRAdminKorektaWRKolor_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "number"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    }
  ],
  "LTRAdminKorektaWRZabudowa_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "number"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    }
  ],
  "LTRAdminKorektaWRRocznik_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "number"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    }
  ],
  "LTRAdminKorektaWRMarka_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "number"
    },
    {
      "name": "col_2",
      "type": "number"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "string"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "number"
    },
    {
      "name": "col_10",
      "type": "number"
    }
  ],
  "LTRAdminUbezpieczenie_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "number"
    },
    {
      "name": "col_2",
      "type": "number"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "string"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "string"
    }
  ],
  "LTRAdminWspolczynnikiSzkodowe_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "number"
    },
    {
      "name": "col_4",
      "type": "number"
    },
    {
      "name": "col_5",
      "type": "string"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "number"
    },
    {
      "name": "col_10",
      "type": "string"
    }
  ],
  "RodzajPaliwa_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "string"
    },
    {
      "name": "col_2",
      "type": "number"
    },
    {
      "name": "col_3",
      "type": "string"
    },
    {
      "name": "col_4",
      "type": "string"
    },
    {
      "name": "col_5",
      "type": "string"
    },
    {
      "name": "col_6",
      "type": "string"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "number"
    },
    {
      "name": "col_10",
      "type": "number"
    },
    {
      "name": "col_11",
      "type": "string"
    }
  ],
  "LTRPrzebiegNormatywny_czak": [
    {
      "name": "col_0",
      "type": "number"
    },
    {
      "name": "col_1",
      "type": "number"
    },
    {
      "name": "col_2",
      "type": "string"
    },
    {
      "name": "col_3",
      "type": "number"
    },
    {
      "name": "col_4",
      "type": "number"
    },
    {
      "name": "col_5",
      "type": "number"
    },
    {
      "name": "col_6",
      "type": "number"
    },
    {
      "name": "col_7",
      "type": "number"
    },
    {
      "name": "col_8",
      "type": "number"
    },
    {
      "name": "col_9",
      "type": "string"
    }
  ],
  "ubezpieczenie_wspolczynniki_szkodowe": [
    {
      "name": "klasa_samar",
      "type": "string"
    },
    {
      "name": "wspolczynnik_szkodowy",
      "type": "number"
    }
  ],
  "v1_admin_parametry": [
    {
      "name": "id",
      "type": "number"
    },
    {
      "name": "nazwa",
      "type": "string"
    },
    {
      "name": "wartosc",
      "type": "number"
    }
  ],
  "v1_admin_ubezpieczenie": [
    {
      "name": "id",
      "type": "number"
    },
    {
      "name": "kolejny_rok",
      "type": "number"
    },
    {
      "name": "stawka_bazowa_ac",
      "type": "number"
    },
    {
      "name": "skladka_oc_wartosc",
      "type": "number"
    },
    {
      "name": "klasa_samar",
      "type": "string"
    }
  ]
};
