ALTER TABLE samar_classes ADD COLUMN IF NOT EXISTS base_mileage_km INTEGER DEFAULT 140000;
ALTER TABLE samar_classes ADD COLUMN IF NOT EXISTS mileage_threshold_km INTEGER DEFAULT 190000;
ALTER TABLE samar_classes ADD COLUMN IF NOT EXISTS base_period_months INTEGER DEFAULT 48;