CREATE TABLE IF NOT EXISTS public.ltr_admin_ubezpieczenia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "KlasaId" BIGINT REFERENCES public.samar_klasa_wr(id) ON DELETE SET NULL,
    "KolejnyRok" INTEGER NOT NULL,
    "StawkaBazowaAC" DOUBLE PRECISION,
    "SkladkaOC" DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS public.ltr_admin_stawka_zastepczy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "KlasaId" BIGINT NULL,
    "SredniaIloscDobWRoku" INTEGER NOT NULL,
    "DobaNetto" DOUBLE PRECISION NOT NULL
);

-- ----------------------------------------------------------------------------
-- MOCK DATA FOR TESTING PURPOSES OF THE CALCULATOR
-- ----------------------------------------------------------------------------
-- Default Fallback dla klas, których nie ma przypisanych
-- KlasaId = NULL, KolejnyRok 1-7, StawkaBazowaAC 2.5%, SkladkaOC 1200 PLN
INSERT INTO public.ltr_admin_ubezpieczenia ("KlasaId", "KolejnyRok", "StawkaBazowaAC", "SkladkaOC") VALUES 
(NULL, 1, 0.025, 1200), 
(NULL, 2, 0.026, 1200), 
(NULL, 3, 0.027, 1200), 
(NULL, 4, 0.028, 1200), 
(NULL, 5, 0.030, 1200), 
(NULL, 6, 0.032, 1200), 
(NULL, 7, 0.035, 1200);

-- Default Fallback dla Auta Zastępczego
-- KlasaId = NULL, Średnio 4 doby w roku, 150 PLN netto za dobę
INSERT INTO public.ltr_admin_stawka_zastepczy ("KlasaId", "SredniaIloscDobWRoku", "DobaNetto") VALUES 
(NULL, 4, 150.0);
