-- Add insurance fields to control_center
ALTER TABLE public.control_center ADD COLUMN IF NOT EXISTS ins_theft_doub_pct numeric(5,4) NOT NULL DEFAULT 0.0500;
ALTER TABLE public.control_center ADD COLUMN IF NOT EXISTS ins_driving_school_doub_pct numeric(5,4) NOT NULL DEFAULT 0.0000;
ALTER TABLE public.control_center ADD COLUMN IF NOT EXISTS ins_avg_damage_value numeric(10,2) NOT NULL DEFAULT 1200.00;
ALTER TABLE public.control_center ADD COLUMN IF NOT EXISTS ins_avg_damage_mileage integer NOT NULL DEFAULT 150000;

-- Create table for Współczynniki Szkodowe
CREATE TABLE IF NOT EXISTS public.ltr_admin_wspolczynniki_szkodowe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    klasa_wr_id BIGINT REFERENCES public.samar_klasa_wr(id) ON DELETE SET NULL,
    wsp_sredni_przebieg numeric(5,2) NOT NULL DEFAULT 1.00,
    wsp_wartosc_szkody numeric(5,2) NOT NULL DEFAULT 1.00
);

-- Basic mock configuration (Fallback for KlasaId = NULL)
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (klasa_wr_id, wsp_sredni_przebieg, wsp_wartosc_szkody)
VALUES (NULL, 1.00, 1.00);
