-- Migration: Create tabela_rabaty for vehicle discount rates
-- Stores per-model discount percentages from manufacturer price lists

CREATE TABLE IF NOT EXISTS public.tabela_rabaty (
    id bigint generated by default as identity primary key,
    marka text NOT NULL,
    model text,
    kod text,
    wykluczenia text,
    rabat double precision
);

COMMENT ON TABLE public.tabela_rabaty IS 'Vehicle discount rates per brand/model from manufacturer price lists';
COMMENT ON COLUMN public.tabela_rabaty.marka IS 'Brand name: SKODA, AUDI, VW Osobowe, VW Dostawcze, SEAT/CUPRA, BMW';
COMMENT ON COLUMN public.tabela_rabaty.rabat IS 'Discount as decimal fraction, e.g. 0.24 = 24%';

ALTER TABLE public.tabela_rabaty ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'tabela_rabaty' AND policyname = 'Enable read access for all users') THEN
        CREATE POLICY "Enable read access for all users" ON public.tabela_rabaty FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'tabela_rabaty' AND policyname = 'Enable insert for all users') THEN
        CREATE POLICY "Enable insert for all users" ON public.tabela_rabaty FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'tabela_rabaty' AND policyname = 'Enable update for all users') THEN
        CREATE POLICY "Enable update for all users" ON public.tabela_rabaty FOR UPDATE USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'tabela_rabaty' AND policyname = 'Enable delete for all users') THEN
        CREATE POLICY "Enable delete for all users" ON public.tabela_rabaty FOR DELETE USING (true);
    END IF;
END $$;
