-- ============================================================================
-- Migration: Rebuild Insurance Tables for 28 SAMAR Classes
-- ============================================================================
-- Drops old tables (with NULL samar_class_id, mismatched column names)
-- Creates new tables with:
--   1. NOT NULL FK to samar_classes
--   2. CamelCase columns matching frozen LTRSubCalculatorUbezpieczenie.py
--   3. Seeds with V1-mapped data (AC 1.5%, OC 1476, damage coefficients)
-- ============================================================================

-- ── STEP 1: DROP old tables ─────────────────────────────────────────────────
DROP TABLE IF EXISTS public.ltr_admin_ubezpieczenia CASCADE;
DROP TABLE IF EXISTS public.ltr_admin_wspolczynniki_szkodowe CASCADE;

-- ── STEP 2: CREATE new insurance rates table ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ltr_admin_ubezpieczenia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    samar_class_id INTEGER NOT NULL REFERENCES public.samar_classes(id) ON DELETE CASCADE,
    "KolejnyRok" INTEGER NOT NULL CHECK ("KolejnyRok" BETWEEN 1 AND 7),
    "StawkaBazowaAC" DOUBLE PRECISION NOT NULL DEFAULT 0.015,
    "SkladkaOC" DOUBLE PRECISION NOT NULL DEFAULT 1476.0,
    UNIQUE(samar_class_id, "KolejnyRok")
);

-- ── STEP 3: CREATE new damage coefficients table ────────────────────────────
-- CamelCase columns to match frozen LTRSubCalculatorUbezpieczenie.py:
--   self.damage_coefficients.get("WspSredniPrzebieg", 1.0)
--   self.damage_coefficients.get("WspWartoscSzkody", 1.0)
CREATE TABLE IF NOT EXISTS public.ltr_admin_wspolczynniki_szkodowe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    samar_class_id INTEGER NOT NULL UNIQUE REFERENCES public.samar_classes(id) ON DELETE CASCADE,
    "WspSredniPrzebieg" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "WspWartoscSzkody" DOUBLE PRECISION NOT NULL DEFAULT 1.0
);

-- ── STEP 4: SEED insurance rates (28 classes × 7 years = 196 rows) ─────────
-- Baseline: AC 1.5% (0.015), OC 1476.0 PLN (confirmed V1 values)
DO $$
DECLARE
    class_id INTEGER;
    yr INTEGER;
BEGIN
    FOR class_id IN SELECT id FROM public.samar_classes ORDER BY id LOOP
        FOR yr IN 1..7 LOOP
            INSERT INTO public.ltr_admin_ubezpieczenia
                (samar_class_id, "KolejnyRok", "StawkaBazowaAC", "SkladkaOC")
            VALUES
                (class_id, yr, 0.015, 1476.0);
        END LOOP;
    END LOOP;
END $$;

-- ── STEP 5: SEED damage coefficients (28 rows) ─────────────────────────────
-- Mapped from V1 seed (klasa_wr_id → samar_class_id)
-- New classes without V1 data get neutral defaults (1.0)
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 0.91, 1.00 FROM public.samar_classes WHERE name = 'Podstawowa - A MINI';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.00, 1.00 FROM public.samar_classes WHERE name = 'Podstawowa - B MAŁE';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.31, 1.00 FROM public.samar_classes WHERE name = 'Podstawowa - C NIŻSZA ŚREDNIA';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.12, 1.00 FROM public.samar_classes WHERE name = 'Podstawowa - D ŚREDNIA';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.00, 1.00 FROM public.samar_classes WHERE name = 'Podstawowa - E WYŻSZA';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 0.91, 1.00 FROM public.samar_classes WHERE name = 'Podstawowa - F LUKSUSOWE';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.00, 1.00 FROM public.samar_classes WHERE name = 'Podstawowa - G SUPER LUKSUSOWE';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.08, 1.00 FROM public.samar_classes WHERE name = 'Vany - B MICROVANY';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.13, 1.00 FROM public.samar_classes WHERE name = 'Vany - C MINIVANY';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.98, 1.00 FROM public.samar_classes WHERE name = 'Vany - D VANY';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.00, 1.00 FROM public.samar_classes WHERE name = 'Vany - E WYŻSZA';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.00, 1.00 FROM public.samar_classes WHERE name = 'Vany - F LUKSUSOWE';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.00, 1.00 FROM public.samar_classes WHERE name = 'Sportowo-rekreacyjne - A MINI';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.00, 1.00 FROM public.samar_classes WHERE name = 'Sportowo-rekreacyjne - B MAŁE';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 0.91, 1.00 FROM public.samar_classes WHERE name = 'Sportowo-rekreacyjne - C NIŻSZA ŚREDNIA';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 0.91, 1.00 FROM public.samar_classes WHERE name = 'Sportowo-rekreacyjne - D ŚREDNIA';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.00, 1.00 FROM public.samar_classes WHERE name = 'Sportowo-rekreacyjne - E WYŻSZA';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 0.91, 1.00 FROM public.samar_classes WHERE name = 'Sportowo-rekreacyjne - F LUKSUSOWE';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.00, 1.00 FROM public.samar_classes WHERE name = 'Sportowo-rekreacyjne - G SUPER LUKSUSOWE';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.00, 1.00 FROM public.samar_classes WHERE name = 'Terenowo-rekreacyjne (SUV) - B MAŁE';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 0.93, 1.00 FROM public.samar_classes WHERE name = 'Terenowo-rekreacyjne (SUV) - C NIŻSZA ŚREDNIA';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 2.62, 1.00 FROM public.samar_classes WHERE name = 'Terenowo-rekreacyjne (SUV) - D ŚREDNIA';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 2.62, 1.00 FROM public.samar_classes WHERE name = 'Terenowo-rekreacyjne (SUV) - E WYŻSZA';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.14, 1.00 FROM public.samar_classes WHERE name = 'Terenowo-rekreacyjne (SUV) - F LUKSUSOWE';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 1.00, 1.00 FROM public.samar_classes WHERE name = 'Terenowo-rekreacyjne (SUV) - G SUPER LUKSUSOWE';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 0.91, 1.00 FROM public.samar_classes WHERE name = 'Kombivany - H KOMBI-VANY';
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody") 
SELECT id, 0.91, 1.00 FROM public.samar_classes WHERE name = 'Minibusy - I MINIBUSY';

-- Wylap klasy, ktore nie znalazly sie w tym wykazie, (szczególnie DOSTAWCZE i NOWE) 
-- i przypisz im neutralny wsspółczynnik (1.000)
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody")
SELECT id, 1.00, 1.00 FROM public.samar_classes c
WHERE c.id NOT IN (SELECT samar_class_id FROM public.ltr_admin_wspolczynniki_szkodowe);

-- ── STEP 6: Indexes ────────────────────────────────────────────────────────
CREATE INDEX idx_ltr_admin_ubezp_class
    ON public.ltr_admin_ubezpieczenia(samar_class_id);
