-- ============================================================================
-- Migration: Rebuild Insurance Tables for 28 SAMAR Classes
-- ============================================================================
-- Drops old tables (with NULL samar_class_id, mismatched column names)
-- Creates new tables with:
--   1. NOT NULL FK to samar_classes
--   2. CamelCase columns matching frozen LTRSubCalculatorUbezpieczenie.py
--   3. Seeds with V1-mapped data (AC 1.5%, OC 1476, damage coefficients)
-- ============================================================================

-- ── STEP 1: DROP old tables ─────────────────────────────────────────────────
DROP TABLE IF EXISTS public.ltr_admin_ubezpieczenia CASCADE;
DROP TABLE IF EXISTS public.ltr_admin_wspolczynniki_szkodowe CASCADE;

-- ── STEP 2: CREATE new insurance rates table ────────────────────────────────
CREATE TABLE public.ltr_admin_ubezpieczenia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    samar_class_id INTEGER NOT NULL REFERENCES public.samar_classes(id) ON DELETE CASCADE,
    "KolejnyRok" INTEGER NOT NULL CHECK ("KolejnyRok" BETWEEN 1 AND 7),
    "StawkaBazowaAC" DOUBLE PRECISION NOT NULL DEFAULT 0.015,
    "SkladkaOC" DOUBLE PRECISION NOT NULL DEFAULT 1476.0,
    UNIQUE(samar_class_id, "KolejnyRok")
);

-- ── STEP 3: CREATE new damage coefficients table ────────────────────────────
-- CamelCase columns to match frozen LTRSubCalculatorUbezpieczenie.py:
--   self.damage_coefficients.get("WspSredniPrzebieg", 1.0)
--   self.damage_coefficients.get("WspWartoscSzkody", 1.0)
CREATE TABLE public.ltr_admin_wspolczynniki_szkodowe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    samar_class_id INTEGER NOT NULL UNIQUE REFERENCES public.samar_classes(id) ON DELETE CASCADE,
    "WspSredniPrzebieg" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "WspWartoscSzkody" DOUBLE PRECISION NOT NULL DEFAULT 1.0
);

-- ── STEP 4: SEED insurance rates (28 classes × 7 years = 196 rows) ─────────
-- Baseline: AC 1.5% (0.015), OC 1476.0 PLN (confirmed V1 values)
DO $$
DECLARE
    class_id INTEGER;
    yr INTEGER;
BEGIN
    FOR class_id IN SELECT id FROM public.samar_classes ORDER BY id LOOP
        FOR yr IN 1..7 LOOP
            INSERT INTO public.ltr_admin_ubezpieczenia
                (samar_class_id, "KolejnyRok", "StawkaBazowaAC", "SkladkaOC")
            VALUES
                (class_id, yr, 0.015, 1476.0);
        END LOOP;
    END LOOP;
END $$;

-- ── STEP 5: SEED damage coefficients (28 rows) ─────────────────────────────
-- Mapped from V1 seed (klasa_wr_id → samar_class_id)
-- New classes without V1 data get neutral defaults (1.0)
INSERT INTO public.ltr_admin_wspolczynniki_szkodowe
    (samar_class_id, "WspSredniPrzebieg", "WspWartoscSzkody")
VALUES
    -- PODSTAWOWA
    (100, 0.91, 1.00),   -- A MINI          (V1 klasa_wr_id=1)
    (101, 1.00, 1.00),   -- B MAŁE          (V1 klasa_wr_id=3)
    (102, 1.31, 1.00),   -- C NIŻSZA ŚREDNIA (V1 klasa_wr_id=7)  ← Octavia
    (103, 1.12, 1.00),   -- D ŚREDNIA       (V1 klasa_wr_id=11)
    (104, 1.00, 1.00),   -- E WYŻSZA        (V1 klasa_wr_id=15)
    (105, 0.91, 1.00),   -- F LUKSUSOWE     (V1 klasa_wr_id=17)
    (106, 1.00, 1.00),   -- G SUPER LUKS.   (NOWA - default)

    -- VANY
    (107, 1.08, 1.00),   -- B MICROVANY     (V1 klasa_wr_id=6)
    (108, 1.13, 1.00),   -- C MINIVANY      (V1 klasa_wr_id=10)
    (109, 1.98, 1.00),   -- D VANY          (V1 klasa_wr_id=14)
    (110, 1.00, 1.00),   -- E WYŻSZA        (NOWA - default)
    (111, 1.00, 1.00),   -- F LUKSUSOWE     (NOWA - default)

    -- SPORTOWO-REKREACYJNE
    (112, 1.00, 1.00),   -- A MINI          (V1 klasa_wr_id=2)
    (113, 1.00, 1.00),   -- B MAŁE          (V1 klasa_wr_id=4)
    (114, 0.91, 1.00),   -- C NIŻSZA ŚREDNIA (V1 klasa_wr_id=8)
    (115, 0.91, 1.00),   -- D ŚREDNIA       (V1 klasa_wr_id=12)
    (116, 1.00, 1.00),   -- E WYŻSZA        (NOWA - default)
    (117, 0.91, 1.00),   -- F LUKSUSOWE     (V1 klasa_wr_id=18)
    (118, 1.00, 1.00),   -- G SUPER LUKS.   (NOWA - default)

    -- TERENOWO-REKREACYJNE (SUV)
    (119, 1.00, 1.00),   -- B MAŁE          (V1 klasa_wr_id=5)
    (120, 0.93, 1.00),   -- C NIŻSZA ŚREDNIA (V1 klasa_wr_id=9)
    (121, 2.62, 1.00),   -- D ŚREDNIA       (V1 klasa_wr_id=13)
    (122, 2.62, 1.00),   -- E WYŻSZA        (V1 klasa_wr_id=16)
    (123, 1.14, 1.00),   -- F LUKSUSOWE     (V1 klasa_wr_id=19)
    (124, 1.00, 1.00),   -- G SUPER LUKS.   (NOWA - default)

    -- KOMBIVANY / MINIBUSY / KEMPINGOWE
    (125, 0.91, 1.00),   -- H KOMBI-VANY    (V1 klasa_wr_id=20)
    (126, 0.91, 1.00),   -- I MINIBUSY      (V1 klasa_wr_id=22)
    (127, 1.00, 1.00);   -- K KEMPINGOWE    (NOWA - default)

-- ── STEP 6: Indexes ────────────────────────────────────────────────────────
CREATE INDEX idx_ltr_admin_ubezp_class
    ON public.ltr_admin_ubezpieczenia(samar_class_id);
